language: node_js
os:
  - linux
  - windows
node_js:
  - "8"
  - "10"
  - "12"
  - "13"

jobs:
  include:
    - stage: coverage
      node_js: "13"
      script:
        - npm t
        - npm run coverage
